// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIyEZTC4Lrym2CmD5mTp4Rzx7iHgasZdw',
    appId: '1:190648765224:web:d771648512eae160715e1d',
    messagingSenderId: '190648765224',
    projectId: 'chatify-88d96',
    authDomain: 'chatify-88d96.firebaseapp.com',
    storageBucket: 'chatify-88d96.appspot.com',
    measurementId: 'G-CYKQM4RD7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjKd7n6XcMMf777nTpIig0k36MGdS94pQ',
    appId: '1:190648765224:android:14b87dd33364c23d715e1d',
    messagingSenderId: '190648765224',
    projectId: 'chatify-88d96',
    storageBucket: 'chatify-88d96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfum4nuldoyvJ_SnPSmKgvfLxtzGB4NIk',
    appId: '1:190648765224:ios:1af69444e9fd091e715e1d',
    messagingSenderId: '190648765224',
    projectId: 'chatify-88d96',
    storageBucket: 'chatify-88d96.appspot.com',
    iosBundleId: 'com.example.chatAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfum4nuldoyvJ_SnPSmKgvfLxtzGB4NIk',
    appId: '1:190648765224:ios:ef542e4f49e39de9715e1d',
    messagingSenderId: '190648765224',
    projectId: 'chatify-88d96',
    storageBucket: 'chatify-88d96.appspot.com',
    iosBundleId: 'com.example.chatAppNew.RunnerTests',
  );
}
